### ISSUE TITLE
Native_Opencv

### ISSUE THREAD

**Issue by arthurgichuhi** [ValYouW/flutter-opencv-stream-processing#5]
First of all great work, really insightful and helpful. I do have a question on as to why Flutter=>Kotlin=>NativeCode using JNI and FFI on the plugin and not just Flutter=>NativeCode using FFI?

**Comment by ValYouW** [comment]
Hi, where do you see Kotlin or JNI?

**Comment by arthurgichuhi** [comment]
I think I might have gotten confused cause I was expecting you to use the OPENCV C++ library cause I was just from seeing another tutorial who built a flutter plugin using a C++ library. Kindly do a video of how you made opencv plugin for flutter if you can, thanks again.

**Comment by arthurgichuhi** [comment]
My bad. I was a bit confused from a previous tutorial. Kindly do a video on how to make a flutter plugin and integrate OPENCV library into it. I have tried to replicate everything you do, gradle sync and make the project, it does it with zero errors but the include folder where I see the opencv library eventually shows up never shows up on my side at all.
